name: test_e_z_v
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  internet_connection_checker_plus: ^1.0.1
  connectivity_plus: ^3.0.2
  get: 4.6.5
  dio: ^4.0.6

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

